### ISSUE TITLE
libopus issue

### ISSUE THREAD

**Issue by syedfahdali** [hurrhnn/raplayer#2]
When I try to run ./build.sh it gets stuck at cloning into libopus at 25%  can you guide me about that or a workaround

**Comment by syedfahdali** [comment]
![Uploading image_2024-01-31_124843273.png…]()

**Comment by hurrhnn** [comment]
maybe internet connection problem? edit ./build.sh, add `-D RAPLAYER_BUILD_DEPS=OFF` and try rebuild it
